### PR TITLE
Fix two usages of slashes

### LINKED ISSUE #12: Should use paths relative to the project
This package uses the paths reported by Atom. But these are absolute to the root of the system, not relative to the project.

For example, my project is at `/user/PLS/projects/awesome`. If I open `awesome` in Atom and if I put `PLS` in the `.atomignore` file, the whole project disappears!

Maybe this package should get the project path and remove this prefix from the paths before giving them to the `ignore` library.

### LINKED ISSUE #13: Trailing slashes prevent from hiding a folder
Say I have `foo/bar`. If I ignore `foo`, `foo` and `bar` are hidden. But if I ignore `foo/`, `bar` is hidden but not `foo`...
That's because Atom provides paths without trailing slash: `/x/y/foo` and `/x/y/foo/bar`.
The `ignore` just applies rules against strings, it won't check existence of a folder or a file.
So to ensure it is working, this package should check if `/x/y/foo` is the path of a folder, and if so, it should add a trailing slash...

### PR DESCRIPTION
**Pull request by PhiLhoSoft**
- Initial slash means "match at root of project";
  handled by removing the path of the current project.
  Fixes #12 
- Trailing slash means "match only if directory";
  handled by adding a trailing slash to the path.
  Fixes #13

### CODE REVIEW

**Comment by leny** [comment]
Thanks.

I'm _very_ busy with pro work today. I'll merge it tomorrow.

File: lib/tree-ignore.js [hunk 1]
```diff
@@ -87,23 +87,32 @@ _fUpdate = function() {
 
     oIgnore = ignore().addIgnoreFile( _oAtomIgnoreFile.getPath() );
 
+    sProjectRoot = "";
+    aTreeEntries = [];
```
Comment (PhiLhoSoft) [inline lib/tree-ignore.js:91]: Remove this line, it is a remnant of some removed code.
I wonder why linter didn't caught it. Isn't IE6 supposed to have "use strict" by default?

**Comment by leny** [comment]
Merged & published as `0.5.0`.
Thanks again.
